document.write("<table width=100% border=0 cellspacing=0 cellpadding=0>");
document.write("	<tr> ");
document.write("	  <td width=20><img src=../images/10x25_trans.gif width=10 height=25></td>");
document.write("	  <td>&nbsp;</td>");
document.write("	</tr>");
document.write("	<tr> ");
document.write("	  <td width=20 height=62>&nbsp;</td>");
document.write("	  <td height=62><a href=../downloads/download.htm><img src=../images/navbar/download_img.gif width=126 height=57 border=0></a></td>");
document.write("	</tr>");
document.write("	<tr> ");
document.write("	  <td><img src=/images/5x5_trans.gif width=5 height=5></td>");
document.write("	  <td><img src=../images/div_dot01.gif width=144 height=5></td>");
document.write("	</tr>");
document.write("	<tr> ");
document.write("	  <td width=20 height=62>&nbsp;</td>");
document.write("	  <td><a href=../photo_gallery/index.htm><img src=../images/navbar/photo_gallery_image.gif width=132 height=56 border=0></a></td>");
document.write("	</tr>");
document.write("	 <tr> ");
document.write("	  <td><img src=../images/5x5_trans.gif width=5 height=5></td>");
document.write("	  <td><img src=../images/div_dot01.gif width=144 height=5></td>");
document.write("	</tr>");
document.write("	<tr> ");
document.write("	  <td width=20 height=66>&nbsp;</td>");
document.write("<td><a href=../videos/index.htm><img src=../images/navbar/video_gallery_image.gif width=146 height=60 border=0></a></td>");
document.write("	</tr>");
document.write(" </table>");				