document.write("<table width=225 border=0 cellspacing=0 cellpadding=0 align=right>");
document.write("<tr>"); 
document.write("<td class=subnav>");
document.write("<a href=/careers/index.htm class=subnav>careers</a>&nbsp;|&nbsp;");
document.write("<a href=/contact_us/contact.aspx class=subnav>contact us</a>&nbsp;|&nbsp;");
document.write("<a href=/contact_us/site_feedback.aspx class=subnav>site feedback</a>");
document.write("</td>");
document.write("</tr>");
document.write("<tr><td height=5></td></tr>");
document.write("</table>");